# format = """
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $elixir\
# $elm\
# $golang\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character
"""

scan_timeout = 10
command_timeout = 2000
# Disable the blank line at the start of the prompt

add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '>_ '
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system

[directory]
# style = "bg:#DA627D"
format = "$path "
truncation_length = 1
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style) $path'
# 
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '$symbol $branch(:$remote_branch) '
 
[git_status]
style = "bg:#FCA17D"
format = '$all_status$ahead_behind '
# 
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [nim]
# symbol = "󰆥 "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [scala]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ♥ $time ]($style)'

